version: '2.3'
services:
  xserver:
    image: devrt/xserver
    ipc: host
    security_opt:
    - seccomp:unconfined
    ports:
    - "12345:80"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X0"]
      interval: "1s"
      retries: 20
  workspace:
    build: ./
    ipc: host
    security_opt:
    - seccomp:unconfined
    network_mode: host
    volumes:
    - ../:/home/ws
    - build:/home/ws/build # keep container pre-build
    - install:/home/ws/install # keep container pre-build
    - log:/home/ws/log # keep container pre-build
    environment:
    - DISPLAY=:0
    - ROS_LOCALHOST_ONLY=1
    - ROS_DOMAIN_ID=42
    volumes_from:
    - xserver
    depends_on:
    - xserver
volumes:
  build:
  install:
  log: